// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0--rc1
// source: api/application.proto

package applicationstatus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApplicationStatusService_GetScore_FullMethodName = "/application_status.ApplicationStatusService/GetScore"
)

// ApplicationStatusServiceClient is the client API for ApplicationStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicationStatusServiceClient interface {
	GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreResponse, error)
}

type applicationStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationStatusServiceClient(cc grpc.ClientConnInterface) ApplicationStatusServiceClient {
	return &applicationStatusServiceClient{cc}
}

func (c *applicationStatusServiceClient) GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScoreResponse)
	err := c.cc.Invoke(ctx, ApplicationStatusService_GetScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationStatusServiceServer is the server API for ApplicationStatusService service.
// All implementations must embed UnimplementedApplicationStatusServiceServer
// for forward compatibility.
type ApplicationStatusServiceServer interface {
	GetScore(context.Context, *GetScoreRequest) (*GetScoreResponse, error)
	mustEmbedUnimplementedApplicationStatusServiceServer()
}

// UnimplementedApplicationStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplicationStatusServiceServer struct{}

func (UnimplementedApplicationStatusServiceServer) GetScore(context.Context, *GetScoreRequest) (*GetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScore not implemented")
}
func (UnimplementedApplicationStatusServiceServer) mustEmbedUnimplementedApplicationStatusServiceServer() {
}
func (UnimplementedApplicationStatusServiceServer) testEmbeddedByValue() {}

// UnsafeApplicationStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationStatusServiceServer will
// result in compilation errors.
type UnsafeApplicationStatusServiceServer interface {
	mustEmbedUnimplementedApplicationStatusServiceServer()
}

func RegisterApplicationStatusServiceServer(s grpc.ServiceRegistrar, srv ApplicationStatusServiceServer) {
	// If the following call pancis, it indicates UnimplementedApplicationStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApplicationStatusService_ServiceDesc, srv)
}

func _ApplicationStatusService_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationStatusServiceServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationStatusService_GetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationStatusServiceServer).GetScore(ctx, req.(*GetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationStatusService_ServiceDesc is the grpc.ServiceDesc for ApplicationStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "application_status.ApplicationStatusService",
	HandlerType: (*ApplicationStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScore",
			Handler:    _ApplicationStatusService_GetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/application.proto",
}
