version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: test-postgres
    environment:
      POSTGRES_DB: test_db_collector
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  migrator:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "sh", "-c",
      "sleep 5 && migrate -path=/migrations -database=postgres://testuser:testpass@postgres:5432/test_db_collector?sslmode=disable up"
    ]
